---
consul_server_config_base_directory: /etc/consul
consul_server_shipped_files: []
# - { name: "", dest: "", force: false, is_volume: true }
consul_server_generated_files: []
# - { name: "", dest: "", src: "", owner: "root", group: "root", mode: "0600", force: true, is_volume: true }
consul_server_template_files:
# - { name: "", dest: "", src: "", owner: "root", group: "root", mode: "0600", force: false, is_volume: true }
- { name: "config/00_consul-config.json", dest: "", src: "consul-config.json.j2", owner: "{{ consul_uid }}", group: "{{ consul_gid }}", mode: "0600", force: true, is_volume: false }
- { name: "config/{{ consul_domain }}-agent-ca.pem", dest: "", src: "agent-ca.pem.j2", owner: "{{ consul_uid }}", group: "{{ consul_gid }}", mode: "0644", force: true, is_volume: false }
- { name: "config/{{ consul_domain }}-agent-ca-key.pem", dest: "", src: "agent-ca-key.pem.j2", owner: "{{ consul_uid }}", group: "{{ consul_gid }}", mode: "0600", force: true, is_volume: false }
- { name: "config/{{ consul_datacenter }}-server-{{ consul_domain }}-$(name).pem", dest: "", src: "server.pem.j2", owner: "{{ consul_uid }}", group: "{{ consul_gid }}", mode: "0644", force: true, is_volume: false }
- { name: "config/{{ consul_datacenter }}-server-{{ consul_domain }}-$(name)-key.pem", dest: "", src: "server-key.pem.j2", owner: "{{ consul_uid }}", group: "{{ consul_gid }}", mode: "0600", force: true, is_volume: false }
- { name: "nginx-master.conf", dest: "/etc/nginx/nginx.conf", src: "nginx-master.conf.j2", owner: "root", group: "root", mode: "0644", force: true, is_volume: true }
- { name: "nginx/nginx.conf", dest: "", src: "nginx.conf.j2", owner: "root", group: "root", mode: "0644", force: true, is_volume: false }
consul_server_config_files: []
# - { name: "", dest: "", src: "", owner: "root", group: "root", mode: "0600", force: false, is_volume: true }
consul_server_config_directories:
# - { name: "", dest: "", owner: "root", group: "root", mode: "0755", force: false, is_volume: true }
- { name: "", dest: "", owner: "root", group: "root", mode: "0755", force: false, is_volume: false }
- { name: "config", dest: "/consul/config", owner: "{{ consul_uid }}", group: "{{ consul_gid }}", mode: "0755", force: false, is_volume: true }
- { name: "nginx", dest: "/etc/nginx/conf.d", owner: "root", group: "root", mode: "0755", force: false, is_volume: true }
consul_server_persistent_volumes:
# - { name: "", dest: "" }
- { name: "data", dest: "/consul/data" }
- { name: "roothome", dest: "/root" }
- { name: "var_run", dest: "/var/run" }
- { name: "nginx_cache", dest: "/var/cache/nginx" }

consul_uid: "100"
consul_gid: "1000"

consul_configs_default:
  encrypt: "{{ consul_encrypt_key|default('Consul=DC1') }}"
  domain: "{{ consul_domain|default('consul') }}."
  datacenter: "{{ consul_datacenter|default('dc1') }}"
  primary_datacenter: "{{ consul_primary_datacenter|default('dc1') }}"
  retry_join: "{{ consul_server_nodes|default([])|product(['8301'])|map('join',':')|list }}"
  performance:
    raft_multiplier: 1
  telemetry:
    prometheus_retention_time: 60s
    disable_hostname: true
  addresses:
    dns: 0.0.0.0
    http: 127.0.0.1
    https: 0.0.0.0
    grpc: 0.0.0.0
  ports:
    dns: 8600
    http: 8500
    https: 8501
    grpc: 8502
    # serf_lan: 8301
    # serf_wan: 8302
    # server: 8300
    # sidecar_min_port: 21000
    # sidecar_max_port: 21255
    # expose_min_port: 21500
    # expose_max_port: 21755
  acl:
    enabled: true
    default_policy: deny
    down_policy: extend-cache
    enable_key_list_policy: true
    enable_token_persistence: true
  ca_file: "/consul/config/{{ consul_domain|default('consul') }}-agent-ca.pem"
  recursors: "{{ network_dns[0].dns4|default([]) + network_dns[0].dns6|default([]) }}"
  # TODO: not host network mode recursors [ 127.0.0.11 ]

# # Service Registration Example
# - set_fact:
#     consul_services: "{{ consul_services|default([]) +
#       [{
#         'id': item.name,
#         'name': 'loki-cassandra',
#         'tags': [
#           item.cassandra_cluster_name,
#           item.cassandra_dc|default('datacenter1'),
#           item.cassandra_rack|default('rack1')
#         ],
#         'meta': {},
#         'address': item.ipv4_address,
#         'port': 9042,
#         'checks': [
#           {
#             'args': ['/bin/sh', '-c', '/usr/bin/curl -f http://'+item.ipv4_address+':3000/hosts 2>/dev/null | /usr/bin/jq -Mr ''.[] | select(.ip == \"'+item.ipv4_address+'\") | .status'' | /bin/grep up' ],
#             'interval': '5s',
#             'timeout': '20s'
#           }
#         ]
#       }] }}"
#   loop: "{{ loki_cassandra_components }}"
