---
privileged_container: yes
shipped_files: []
generated_files:
- { container_path: "/etc/eos.keytab", host_dir: ".", host_file: "eos.keytab", src_base: "tmp/keytab/{{ eos_realm }}", src_file: "eos.keytab", owner: "daemon", group: "daemon", mode: "0400" }
template_files:
- { container_path: "/etc/sysconfig/eos", host_dir: "./sysconfig", host_file: "eos", template_file: "eos.sysconfig.j2", owner: "root", group: "root", mode: "0644" }
- { container_path: "/etc/xrootd/xrootd-fwd-proxy.cfg", host_dir: "./xrootd", host_file: "xrootd-fwd-proxy.cfg", template_file: "xrootd-fwd-proxy.cfg.j2", owner: "root", group: "root", mode: "0644" }
- { container_path: "/etc/krb5.conf", host_dir: ".", host_file: "krb5.conf", template_file: "krb5.conf.j2", owner: "root", group: "root", mode: "0644" }
- { container_path: "/eos_proxy_setup.sh", host_dir: ".", host_file: "eos_proxy_setup.sh", template_file: "eos_proxy_setup.sh.j2", owner: "root", group: "root", mode: "0755" }
persistent_volumes:
- { name: "roothome", dest: "/root" }
- { name: "eos", dest: "/var/eos" }
- { name: "spooleos", dest: "/var/spool/eos" }
- { name: "spoolxrootd", dest: "/var/spool/xrootd" }
- { name: "log", dest: "/var/log/eos" }
